package com.wds.java.cxf.client.role.code;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-02-21T14:09:25.788+08:00
 * Generated source version: 3.0.0-milestone1
 * 
 */
@WebServiceClient(name = "ISecurityServiceService", 
                  wsdlLocation = "http://localhost:8080/web/services/SecurityService?wsdl",
                  targetNamespace = "http://server.spring.cxf.wds.com/") 
public class ISecurityServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.spring.cxf.wds.com/", "ISecurityServiceService");
    public final static QName ISecurityServicePort = new QName("http://server.spring.cxf.wds.com/", "ISecurityServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/web/services/SecurityService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ISecurityServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/web/services/SecurityService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ISecurityServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ISecurityServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISecurityServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ISecurityServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ISecurityServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ISecurityServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ISecurityService
     */
    @WebEndpoint(name = "ISecurityServicePort")
    public ISecurityService getISecurityServicePort() {
        return super.getPort(ISecurityServicePort, ISecurityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISecurityService
     */
    @WebEndpoint(name = "ISecurityServicePort")
    public ISecurityService getISecurityServicePort(WebServiceFeature... features) {
        return super.getPort(ISecurityServicePort, ISecurityService.class, features);
    }

}
