
package com.wds.java.cxf.client.role.code;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-02-21T14:09:25.740+08:00
 * Generated source version: 3.0.0-milestone1
 * 
 */
public final class ISecurityService_ISecurityServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.spring.cxf.wds.com/", "ISecurityServiceService");

    private ISecurityService_ISecurityServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ISecurityServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ISecurityServiceService ss = new ISecurityServiceService(wsdlURL, SERVICE_NAME);
        ISecurityService port = ss.getISecurityServicePort();  
        
        {
        System.out.println("Invoking getAuthority...");
        com.wds.java.cxf.client.role.code.MappingUserValue _getAuthority__return = port.getAuthority();
        System.out.println("getAuthority.result=" + _getAuthority__return);


        }

        System.exit(0);
    }

}
