
package com.wds.java.cxf.client.user.code;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-02-21T15:32:23.962+08:00
 * Generated source version: 3.0.0-milestone1
 * 
 */
public final class IUserService_UserServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.server.spring.cxf.wds.com/", "UserService");

    private IUserService_UserServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserService ss = new UserService(wsdlURL, SERVICE_NAME);
        IUserService port = ss.getUserServiceImplPort();  
        
        {
        System.out.println("Invoking getUserName...");
        java.util.List<java.lang.String> _getUserName__return = port.getUserName();
        System.out.println("getUserName.result=" + _getUserName__return);


        }

        System.exit(0);
    }

}
