package com.wds.java.cxf.client.user.code;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-02-21T15:32:24.003+08:00
 * Generated source version: 3.0.0-milestone1
 * 
 */
@WebService(targetNamespace = "http://server.spring.cxf.wds.com/", name = "IUserService")
@XmlSeeAlso({ObjectFactory.class})
public interface IUserService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserName", targetNamespace = "http://server.spring.cxf.wds.com/", className = "com.wds.java.cxf.client.user.code.GetUserName")
    @WebMethod
    @ResponseWrapper(localName = "getUserNameResponse", targetNamespace = "http://server.spring.cxf.wds.com/", className = "com.wds.java.cxf.client.user.code.GetUserNameResponse")
    public java.util.List<java.lang.String> getUserName();
}
